### GET (Basic)
http://localhost:5000

### GET Projects (ALL)
http://localhost:5000/api/projects

### GET Actions (ALL)
http://localhost:5000/api/projects/1/actions

### GET Projects (by ID)
http://localhost:5000/api/projects/1

### GET Actions (ID)
http://localhost:5000/api/projects/2/actions/4

### POST (Projects)
POST http://localhost:5000/api/projects HTTP/1.1
content-type: application/json

{
  "name": "Test Project",
  "is_complete": false
}

### POST (Actions)
POST http://localhost:5000/api/projects/1/actions HTTP/1.1
content-type: application/json

{
  "description": "Test #2",
  "project_id": 1,
  "notes": "Testing, testing...",
  "is_complete": false
}

### PUT
PUT http://localhost:5000/api/projects/1/actions/1 HTTP/1.1
content-type: application/json

{
  "description": "Project Kick-off",
  "project_id": 1,
  "notes": "Initiate project",
  "is_complete": false
}

### DELETE Projects
DELETE http://localhost:5000/api/projects/

### DELETE Actions
DELETE http://localhost:5000/api/projects/1/actions/3


